language: csharp
mono: none
os: linux
dotnet: 3.1
script:
    - dotnet build -c Release
    - dotnet pack -c Release
deploy:
    - provider: script
      skip_cleanup: true
      script: dotnet nuget push Logging.MSTeams/bin/Release/Logging.MSTeams.*.nupkg --api-key $NUGET_API_KEY --source nuget.org
      on:
          tags: true
          branch: master
